# This pipeline is triggered upon making a PR against the main branch.
# Unit tests are defined under mlops_example_1/tests
# The integration test deploys and runs the model_training_job defined in mlops_example_1/resources/model-workflow-resource.yml
# This integration test is run in the staging workspace, as defined under mlops_example_1/databricks.yml

# run on merge requests, tags, and the default branch
stages:
  - triggers

image: registry.gitlab.com/TODO:latest

trigger_ci:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/pipelines/mlops_example_1-bundle-ci.yml
    strategy: depend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'
      changes:
        - mlops_example_1/*

trigger_cd_stage:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/pipelines/mlops_example_1-bundle-cd-staging.yml
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == 'main'

trigger_cd_production:
  stage: triggers
  trigger:
    include:
      - local: .gitlab/pipelines/mlops_example_1-bundle-cd-prod.yml 
    strategy: depend
  rules:
    - if: $CI_COMMIT_BRANCH == 'release'